FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir \
    torchvision==0.18.1+cpu \
    -f https://download.pytorch.org/whl/cpu/torch_stable.html

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install numpy fastapi Pillow uvicorn python-multipart

EXPOSE 80

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]